### ISSUE TITLE
Feature request // Dynamic path to pom.xml

### ISSUE THREAD

**Issue by saschask** [MashupMill/sync-pom-version-to-package#18]
Hello,

as far as I could see in the code, the `pom.xml` is expected to be in the same folder as the `package.json`. In our project, the `pom.xml` is inside another folder which is why we would need to pass the path to it dynamically to _sync-pom-version-to-package_.

Currently expected by _sync-pom-version-to-package_: 
`./package.json`
`./pom.xml`

Structure in our project:
`./frontend/package.json`
`./aem/pom.xml`

Would it be possible to add such a new option in some way to _sync-pom-version-to-package_ to enable users to pass dynamic paths?

Thanks already for your feedback on that,
Sascha

**Comment by ammmze** [comment]
Oops...guess I forgot to update the readme when I added the ability to set the paths a while back. But I believe you should be able to specify paths with `--pom-file` and `--package-file`. Let me know if that works for you 👍 https://github.com/MashupMill/sync-pom-version-to-package/blob/859fa530a7f5039ca7d0ab7fd49a48604dabb301/src/cli.js#L8-L9

**Comment by saschask** [comment]
Hey @ammmze, thanks a lot for this hint. I tried it out and indeed using the parameters mentioned by you enabled me to define different paths for the files. Well, at least I tried the pom.xml parameter since that's the one I needed and that was working like a charm.

Would be nice to see this in the README.md so others do not need to search for it in the issues.

Best regards
Sascha

**Comment by ammmze** [comment]
Glad to hear it worked it. I've updated the readme to document those options.
