### ISSUE TITLE
readPomVersion should read parent version section when version is absent

### ISSUE THREAD

**Issue by pcavezzan** [MashupMill/sync-pom-version-to-package#2]
When you are in a multi module context, you often have a parent pom who own common project properties such as version. In that case, version section is absent from child pom.xml.

So it would be nice to read from that section when no version could be read from pom.

I'm preparing a fix for that and will send you pretty soon 😃

**Comment by ammmze** [comment]
Thanks for the PR :) This has been merged and is available starting with `v1.3.0`
